### ISSUE TITLE
Support new NWC file which are NWCtxt with a deflated header

### ISSUE THREAD

**Issue by lasconic** [lasconic/nwc2musicxml#11]
See https://github.com/lasconic/nwc2musicxml/issues/8#issuecomment-157135032

**Comment by nwsw** [comment]
Essentially, the deflated data starts immediately after the "[NWZ]\0" header. The inflated stream starts with some binary data, which just enables older NWC programs to recognize the file as being from a newer version. 

The actual standard nwctxt starts with `!NoteWorthyComposer` as you would expect.

You can see this for yourself using the following `bash` command on any NWC 2.75 *.nwc file:

```bash
(printf "\x1f\x8b\x08\x00\x00\x00\x00\x00"; tail -c +7 file.nwc) | gzip -dc > file.nwctxt
```

**Comment by lasconic** [comment]
Any chance you link to a 2.75 nwc file?

**Comment by nwsw** [comment]
Does this help?

[v275.zip](https://github.com/lasconic/nwc2musicxml/files/245525/v275.zip)

**Comment by lasconic** [comment]
Yes! I can deflate this.

**Comment by lasconic** [comment]
But sure, go ahead.

**Comment by lasconic** [comment]
```
byte buffer[] = new byte[COMPRESS_HEADER.length() + 1];
		try {
			IOUtils.read(is, buffer, 0, COMPRESS_HEADER.length() + 1);
			InflaterInputStream in = new InflaterInputStream(is);
			BufferedReader input = new BufferedReader(new InputStreamReader(in, "UTF-8"));
			try {
				String line = null; // not declared within while loop

				while ((line = input.readLine()) != null) {
					System.out.println(line);
				}
			} finally {
				input.close();
			}

		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
```
