### ISSUE TITLE
Add support for Segno and Coda

### ISSUE THREAD

**Issue by lasconic** [lasconic/nwc2musicxml#14]

**Comment by hedgert** [comment]
I've made changes to support Segno and Coda - I created a new Flow type (mirroring the use of NWC groups of functionality in a single class) to provide the different XML tags required in the direction-type and sound nodes of the XML.
I've tested with NWC files saved as NWCTXT converted and then viewed in Sibelius First - and the results were as I expected.  Is there a definitive test of MusicXML output - is confirming with Sibelius sufficient?

**Comment by lasconic** [comment]
Sibelius will do. Finale was known to have a better MusicXML import. You could test with MuseScore, it's free and it will also validate (in XSD meaning of the term) the MusicXML files on import and warn you if there are errors. 

Could you also attached a simple snippet of NWCtxt to this issue? It could be the first piece of our test suite...

**Comment by lasconic** [comment]
Done 5db52dda8173674e8b00d5f26605455ea51bc4a6
