### ISSUE TITLE
Add support for Voltas

### ISSUE THREAD

**Issue by lasconic** [lasconic/nwc2musicxml#15]

**Comment by hedgert** [comment]
I've coded handling of Voltas - however, there is one type that NWC appears to handle but I don't see reference to in MusicXML documentation and Sibelius doesn't seem to handle it.
It's a type of ending "D" (default ending according to NWC) - and it's used for a final repeat after DS/DCs have happened - NWC handles the flow for it - and I've coded it into MusicXML but Sibelius ignores a "D" numbered ending - not sure if that's because Sibelius doesn't implement MusicXML properly - or whether NWC have created something that isn't standard - any thoughts?
The screenshot I've attached is an NWC example file for voltas and you can see the 2,D ending in bar 6.  What NWC does is to use that "Default" ending when it repeats after the DSalCoda back to the Segno - i.e. after the return to the Segno it uses the D labelled ending.

![screen shot 2016-05-07 at 18 46 57](https://cloud.githubusercontent.com/assets/19214162/15093578/40a0626e-1484-11e6-81fd-6447ebf65ca7.png)

**Comment by lasconic** [comment]
I never saw a D. indication. I checked *Behind Bars* by Ellen Gould, regarded as a reference for music engraving, and there is no mention about D, so I guess it's an invention of NWC. Maybe @nwsw can confirm?
Since it's in the original, it's ok to put it in the MusicXML but I wouldn't expect a MusicXML importer to do anything useful with it, except for display.

**Comment by hedgert** [comment]
OK - then I'll leave D in the MusicXML.
I attach the nwctxt that is the equivalent of the NWC file above.
[REPEAT4.txt](https://github.com/lasconic/nwc2musicxml/files/253581/REPEAT4.txt)

**Comment by hedgert** [comment]
Is this another NWC special?  A number in brackets about a repeat close bar - which NWC interprets as going back to the previous section open and repeating the bars in between the number of times in the brackets.  I can't find anything in MusicXML for this (although the flow control is there - the visual indication doesn't seem to be, so I wonder if this is non-standard/not MusicXML)?
<img width="52" alt="screen shot 2016-05-07 at 22 01 28" src="https://cloud.githubusercontent.com/assets/19214162/15094560/b27daa70-149f-11e6-9d44-68794c0801c4.png">

**Comment by lasconic** [comment]
The flow control, I gather you are talking about ?http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#CT-MusicXML-repeat.htm

For the text, I can't find anything in Gould but I have seen 3x in many scores. I guess the text could be converted to a simple direction text.

**Comment by hedgert** [comment]
Thanks - I'll code 3x in place of (3) that NWC exports.

NB I'm trying, as discussed, to introduce some tests for what I'm adding - and diff-ing files does seem the easiest way.  You've got an IOUtils.java class, which has a contentEquals method that appears to do diff - but although it looks perfectly sensible it doesn't seem to work.  Even when I put the output file from the last run as the comparison file, it tells me the two files are different.  Is it a utility you've used elsewhere?

**Comment by hedgert** [comment]
I'm working on the repeat (3x) and I'm not sure either Sibelius or MuseScore are doing the right thing - before we even get to the repeat - that I think the MusicXML does support.
This is my NWC input file:
[TestLocalRepeatCloseRepeat3.pdf](https://github.com/lasconic/nwc2musicxml/files/254072/TestLocalRepeatCloseRepeat3.pdf)
So it has a section bounded by local section open close bars - and the (3) annotation - but ignore the (3) for now.
The bar lines bounded bars 2-4 are light-light.
Sibelius renders the XML (which I attach below) as (with heavy-heavy barlines):
![screen shot 2016-05-08 at 20 26 52](https://cloud.githubusercontent.com/assets/19214162/15099906/5c2e465e-155b-11e6-829e-df84ccca0206.png)
And MuseScore renders it with light-light barlines but no without the double dots for the repeat:
![screen shot 2016-05-08 at 20 26 58](https://cloud.githubusercontent.com/assets/19214162/15099909/717379d0-155b-11e6-871b-7b0096694e78.png)

So to my untrained eye - I think they're both wrong - given the XML I've generated.  Am I misunderstanding the light-light barline repeats (if so does that mean that NWC's use of them is non-standard)?

Generated XML that I've loaded into both Sibelius and MuseScore is:

[LocalRepeatCloseRepeat3.txt](https://github.com/lasconic/nwc2musicxml/files/254073/LocalRepeatCloseRepeat3.txt)

**Comment by hedgert** [comment]
I think I’m done - but extending my testing to double staves (I’ve testing everything on a single stave so far).
I’ve added voltas, fermata/breath marks and the various tempo variances (in NWC those are grouped together for some reason), segnos and I’ve implemented repeating bars (i.e. a pair of double barlines with dots opening and the later closing with a direction to repeat that set of bars n times.  Interestingly Sibelius has a bug and doesn’t handle that correctly (you can write it in Sibelius, but even if you export as MusicXML and re-read Sibelius’ own XML back in it doesn’t work) but your MuseScore does handle it correctly.
I’ve changed one thing about your implementation in my version (for the repeating bars above): NWC has light-light bars with double dots. Sibelius converts these into heavy-light then light-heavy with dots.  MuseScore just interprets them as light double bar lines with no dots.  So neither does what NWC does (offering to repeat a block of bars between light-light double dotted barlines).  Given that - where your code interprets the various bar types, where NWC codes LocalRepeatOpen and LocalRepeatClose I’ve implemented as heavy-light and light-heavy with a repeat - only for the repeat.  Given neither Sibelius nor MuseScore can handle light-light repeats, I don’t believe this takes anything away and it does add support for a block of bars repeated.  You can see this in action in my test Nwc2MusicXMLTest_LocalRepeats.java

I’ve added tests for everything I’ve done using JUnit.  As you suggested I’ve used a file diff, so if the test fails it doesn’t tell you why - but it does provide assurance as code is changed in the future that these continue to work.  And if you want to see what the actual differences are you can use unix diff.

As I say I need to run some tests to ensure that multiple staves work - particularly with voltas.  And for that I have a question about the style of your code that I should follow.  NWC can produce nonsense music (in nwctxt and musicXML) as it allows you to put different voltas on different staves.  NWC even plays the staves independently if that happens - i.e. you see/hear the highlighted note playing in a different bar on different staves at the same time.
So my question is: given NWC produces that nonsense, should I just faithfully translate the nonsense into XML (not sure what Sibelius or MuseScore will do with it) or should I reject it - which I could most easily do by only coding the voltas on the first staff across all staves - which would ensure they are all the same.  Or something else?

If I’m understanding correctly having done Github commits so far for all my changes, once I’m finished with the above, I push - and then you can see my fork?  And I’m assuming you validate what I’ve done in some way before you choose to put the code back into the main branch?

Thanks
Tim

**Comment by lasconic** [comment]
Never saw a Light Light repeat. It must be a NWC particularity. So I believe your decision.

Junit, diff, sounds perfect.

Using voltas in the top staff makes sense... too bad if a user wrote some nonsense. We have the same problem a little bit everywhere in this project since it's also possible to put too many notes or not enough in a measure for example...


I see your fork here https://github.com/hedgert/nwc2musicxml but I don't see your commits, so you probably commit only in your local repository. Hopefully on a branch. You can then push your branch on github with git push origin yourbranch (assuming you set the origin and the name of your branch is "branch"). Then you can indeed do a pull request, I will review the code (mainly compile it and run it on a couple of files...) and integrate it in the main repository (mine) in the master branch.

**Comment by hedgert** [comment]
Thanks Nicholas.
I forked and then coded and locally committed - no branch.  I thought fork was giving me a separate code base to work on that could be merged later - obviously more to learn about GitHub!  But I'll see if I can fix that locally by doing a branch (on another machine where I don't have my local repository) and then checking my changes into the branched version rather than what I've done so far.

And thanks for the guidance on voltas - I'll make the changes to implement that.

Regards Tim

**Comment by hedgert** [comment]
I've now created a branch merged my files into it - confirmed the tests all work and then pushed to the branch.
Next step is the multi-stave testing and the changes required to repeat voltas from the first staff across all staves.

**Comment by hedgert** [comment]
Mmm - how far should I take the "apply the top staff voltas" principle? In creating some test files before looking st the code changes, I took my 2 stave test and inserted an extra bar so the voltas are out of line - and then of course the repeat bar lines (eg light-heavy double dotted at the end of the 1st ending Volta were out of line too. Should I cover barline types as well?  Effectively that would mean as we go through the first stave storing the bar lines and the voltas - and I guess the segnos too - and then using that stored set instead of what's actually on subsequent staves.  Is that taking too far the possibility that someone produces a daft NWC file?

**Comment by hedgert** [comment]
MuseScore is more picky than Sibelius - but in this instance is it right to be?
In testing my Votlas I find all is well the MusicXML is as I expected and Sibelius reads/displays and plays back correctly - but MuseScore rejects the XML as invalid - this is the issue:
Support for closing a volta consists of adding a <bar-style> stag to <barline>  And where <barline> is already defined (as at the end of the bar), then I add it to the existing <barline> that NWC2MusicXML was already creating - my addition goes in before what is already there:
![screen shot 2016-05-11 at 22 21 31](https://cloud.githubusercontent.com/assets/19214162/15197051/4a7e0868-17c7-11e6-89cb-75fef26f22a7.png)
Sibelius handles it, MuseScore rejects it saying:
![screen shot 2016-05-11 at 22 25 01](https://cloud.githubusercontent.com/assets/19214162/15197068/5bb6a2c0-17c7-11e6-979e-6cb9d15aa530.png)
If I swap the order of the <ending and <bar-style tags round, then MuseScore loads and displays correctly.  (Interestingly it looks like MuseScore doesn't handle the variety of possible voltas - a conventional 1-ending, then 2-ending is OK, but my test of 1,2-ending and 3-ending isn't handled properly (1st ending is played then on the 2nd ending it plays through the 1,2 time bar and then straight through the repeat barline and through the 3rd ending) - I appreciate these are MuseScore comments and I'll raise them elsewhere once I've dealt with this.
So MuseScore loads and displays this version correctly:
![screen shot 2016-05-11 at 22 21 12](https://cloud.githubusercontent.com/assets/19214162/15197280/66970062-17c8-11e6-9064-d6398cfcd831.png)

But surely the order of <bar-style and <ending within <barline doesn't matter from a pure XML perspective?
So my question is, is it valid MusicXML either way round, (in which case MuseScore is overly picky) or is it correct that the order has to be <bar-style first and then <ending

**Comment by lasconic** [comment]
MuseScore is validating the MusicXML with the standard XSD schema... barline is defined with a xs:sequence with bar-style first and ending next http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#CT-MusicXML-barline.htm As far as I understand elements in a sequence must appear in order http://www.w3schools.com/xml/el_sequence.asp and so MuseScore enforces that.

**Comment by hedgert** [comment]
Thank you - a bit more coding to do then!
Can you comment on my previous post - about how far to go in taking direction from the top staff with voltas?

**Comment by lasconic** [comment]
About top staff voltas, I don't really have a strong opinion. If there are different **repeat** barlines, volta or coda/segno on different staves, we somehow need to choose. Question is: do we choose at export time or at import time...? Maybe it's not the job of the converter to decide if it's semantically good and it should just try to export as a much information as possible to MusicXML? Or it should take the job, and in this case, yes, take the first (visible?) staff as a reference or make sure that the information is not contradictory between the different staves...

I understand I ask more questions that I give answers :)

**Comment by hedgert** [comment]
Thanks Nicholas - I don't mind there not being strong opinions I just want to make sure that if there are, I respect them.

Regarding the below it makes me think about my previous proposal - certainly if I do take the top stave I think pointing it out makes sense. But that makes me think - what's the point of forcing the first stage on the other staves - while it may give XML that is technically correct, presumably something has gone wrong with the original music in NWC - and me just aligning voltas, segnos and barlines with the first stave won't fix that, it might even hide it. As now it will be less visually obvious that the original NWC had problems.
So maybe the better approach is to convert faithfully and report the issues - so attention is drawn to bad nwctxt before the user gets to their next music app.

You mention tests you'll do before you publish. If there are particular test files you use, would you share them? I can then add JUnit tests for them to make sure before I finish my changes that I haven't broken anything?

Thanks Tim

**Comment by lasconic** [comment]
I don't have many files and most of them are from people sending bug reports, so I don't feel confortable to share them :-/

**Comment by hedgert** [comment]
I did a pull request and checked all my changes and tests in about a week ago.
I fully appreciate you'll need time to review, but not having heard from you, I wanted to check that you're aware/that I haven't done my pull request wrongly!

**Comment by lasconic** [comment]
Hi, sorry for the silent week. I will try to take a closer look this week end.

**Comment by lasconic** [comment]
Done.  5db52dda8173674e8b00d5f26605455ea51bc4a6
