### ISSUE TITLE
Missing notes in second voice

### ISSUE THREAD

**Issue by aksarben** [lasconic/nwc2musicxml#24]
When I converted **http://www.hymntime.com/tch/nwc/a/m/a/Amazing%20Grace.nwc** to XML, it added slurs/ties that are not in the original score. The **desired** appearance is here: 

**http://www.hymntime.com/tch/pdf/a/m/a/Amazing%20Grace.pdf**

Dick Adams

**Comment by lasconic** [comment]
Thank you for the report. Actually some voice 2 notes are completely missing. Good catch.

**Comment by lasconic** [comment]
Should be fixed now. Note that measure 8 in this score has 4 beats instead of 3.
