### ISSUE TITLE
Diacritic characters not correctly converted

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lasconic/nwc2musicxml#6]
```
What steps will reproduce the problem?
1. Create lyrics with diacritic characters like éèà etc.
2.
3.

What is the expected output? What do you see instead?

The characters are shown as question marks "?"

What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `bersy...@gmail.com` on 16 Feb 2012 at 4:21

Attachments:
* [M0001_le_port_de_tacoma.nwctxt](https://storage.googleapis.com/google-code-attachments/nwc2musicxml/issue-6/comment-0/M0001_le_port_de_tacoma.nwctxt)

**Comment by lasconic** [comment]
This is not fixed e1922aa
