### ISSUE TITLE
NWC 2.75 -- Now supports unicode

### ISSUE THREAD

**Issue by lasconic** [lasconic/nwc2musicxml#8]
Current version of the converter expects the file to be Cp1252, now NWC seems to export UTF-8 with a BOM.

**Comment by nwsw** [comment]
Yes, you can process the 2.75 nwctxt files as utf-8. There isn't a BOM. 

Also, *.nwc files are now just deflated nwctxt with a header.

**Comment by lasconic** [comment]
Fixed e1922aa3abf69850113e6edae3c698914e46bc1b

**Comment by lasconic** [comment]
Let me open an issue to support NWC files.
